Add organizer dashboard
coderdojobraga/shuriken pull request #129
Opened 2023-01-05 19:08 UTC by RuiL1904

2023-01-23 12:36 UTC, MarioRodrigues10 requested changes
Make sure it's possible to activate an account even if the user isn't registered yet

2023-02-06 10:49 UTC, MarioRodrigues10 approved these changes

2023-02-19 01:30 UTC, MarioRodrigues10 approved these changes

2023-03-03 10:14 UTC, ruioliveira02 approved these changes
Just wait for bokken to be deployed before merging :pray:

2023-03-03 11:47 UTC, merged