Add FAQ's Page
coderdojobraga/shuriken pull request #160
Opened 2023-03-14 12:03 UTC by pedrofp4444

2023-03-14 12:07 UTC, pedrofp4444 commented
I liked the result, I'm just having some trouble, because I wanted to, when opening a disclosure, to close the others until I understood that the specific feature I described is predefined but it's not working :disappointed:

2023-03-14 12:09 UTC, pedrofp4444 commented
Also, how can I surpass the tests once that I used a new component, which means more packages, locally I run ```npm install @headlessui/react```. How can I add them to the tests so that they pass?

2023-03-14 16:42 UTC, RuiL1904 commented
@pedrofp4444 You need to install the dependency only on the `web` app.
`npm remove @headlessui/react` on the root of the repo and then `npm install @headlessui/react` on the root of the `web` app.

2023-03-14 20:51 UTC, MarioRodrigues10 requested changes
Here are some question i think you should add:
"Quero ser voluntário! Quais são as opções?" - Ser ou não mentor 
"Como funciona uma sessão?"
"Quais são as responsabilidades e conhecimentos necessários em um voluntário?"

2023-03-18 08:43 UTC, MarioRodrigues10 requested changes
Could you please convert the ```faqs.js``` page in tsx.
You just need to change the file extension, there will be no conflicts.

2023-03-18 08:43 UTC, MarioRodrigues10 commented on apps/web/pages/faqs.js
> +import React, { useState } from "react";
```suggestion
```

2023-03-18 18:25 UTC, MarioRodrigues10 approved these changes

2023-03-18 18:25 UTC, merged