✨ Add team section
coderdojobraga/shuriken pull request #25
Opened 2021-08-23 20:38 UTC by feliciofilipe

Added a team section to the landing. Note that the footer is in the
wrong color - this fix is pending on #24.

2021-08-23 22:38 UTC, nelsonmestevao commented on data/team.json
> +        "role": "Diretor de Curriculo e Material"
```suggestion
        "role": "Responsável do Currículo e Material"
```

2021-08-23 22:38 UTC, nelsonmestevao commented on landing/Header/index.js
> +            <a href="team">
Use Link component from `next/link` to navigate between pages.

2021-08-23 22:38 UTC, nelsonmestevao commented on landing/Header/index.js
> +                <a href="./team.js">
```suggestion
                <a href="./team">
```

2021-08-25 11:51 UTC, nelsonmestevao commented on pages/team.js
> +import team from "data/team.json";
```suggestion
import team from "~data/team.json";
```

2021-08-25 13:11 UTC, nelsonmestevao commented on landing/Header/index.js
> +                <a href="./team">Equipa</a>
```suggestion
                <Link href="/team">Equipa</Link>
```

2021-09-06 11:21 UTC, nelsonmestevao requested changes
Missing things:

- [x] The content should align with the limits of navbar and footer;
- [x] The breakpoints should be improved, for example, on mobile should be one person per row, and the description should also decrease its font size as the title does;
- [x] We need a description;
- [ ] The "Saber mais" button should not have transparent background around and the text on hover shouldn't be blue.

2021-09-06 11:22 UTC, nelsonmestevao commented on styles/Home.module.css
> +    transform: translate(0%, 1435.5px);
```suggestion
    transform: translate(0%, 1435px);
```

2022-08-30 19:30 UTC, ruioliveira02 approved these changes

2022-08-30 23:28 UTC, merged