:art: Add koifish animation to the login/register
coderdojobraga/shuriken pull request #31
Opened 2021-09-03 20:42 UTC by feliciofilipe

Adds a Koi Fish animation to the login and register forms.

To note that the way it is implemented (with JQuery) it is not the desirable one but it works.
A medium to long goal should be to rewrite this feature.

![Screenshot 2021-09-03 at 21-33-45 CoderDojo Braga](https://user-images.githubusercontent.com/55213469/132063247-186c81ad-d87d-4db9-96a9-3ba24a0c8d40.png)

2021-09-03 22:10 UTC, nelsonmestevao commented on components/Login/index.js
> +      <div id="fishesHolder" class="fishesHolder"></div>
```suggestion
```

2021-09-03 22:10 UTC, nelsonmestevao commented on pages/login.js
> +    <>
```suggestion

```

2021-09-03 22:10 UTC, nelsonmestevao commented on pages/login.js
> +    </>
```suggestion
```

2021-09-03 22:11 UTC, nelsonmestevao commented on pages/login.js
> +        <Script src="/vendor/koi-animation.js" />
Move this inside AuthenticationLayout.

2021-09-03 22:12 UTC, nelsonmestevao requested changes
It looks amazing and super cute! :tropical_fish: 

:stop_sign: Unfortunately, this still breaks mobile.

It's a little bit heavy, maybe we will need to reduce the number of fishs.

2021-09-06 09:56 UTC, nelsonmestevao commented
Maybe the easiest way to fix on mobile is to  not show it :thinking:

2021-09-11 10:38 UTC, miguelbrandao commented
I think it looks pretty cute and fun, but it almost doubles the download size (from about 250kB to 430kB).

Besides, I think there are too many fishes; a third or a quarter should be enough. This should also prevent performance issues in lower spec machines, although this is only a concern, as I have not tested it.

On another point, I agree with @nelsonmestevao  that this should be a component. Also, if we are going to merge this, I think we should be honest with ourselfs: this will probably never be rewritten and will remain jQuery for all of eternity :joy:

2021-09-11 11:20 UTC, nelsonmestevao commented
We probably can stop this being downloaded on mobile too. At least on mobile it would be good to save some bandwidth.

2021-09-14 13:04 UTC, nelsonmestevao approved these changes
Really cool 🐠🐟🐡

2021-09-14 13:07 UTC, merged